run:
  timeout: 5m
linters:
  enable:
    - errcheck # Check for unchecked errors
    - gosimple # Simplify code
    - govet # Examine Go code for suspicious constructs
    - ineffassign # Detect ineffectual assignments
    - staticcheck # Advanced static analysis
    - typecheck # Like the front-end of a Go compiler
    - unused # Check for unused constants, variables, functions and types
