name: Go Build and Test

on:
  push:
    branches: ["main"]
    paths:
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "cmd/**"
      - "pkg/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"
jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run golangci-lint on root module
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: .

      - name: Run golangci-lint on pkg module
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: ./pkg

  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Set up Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /tmp/go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-cache-

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run tests on root module
        run: gotestsum --format testname -- ./...
        env:
          GOCACHE: /tmp/go-build-cache

      - name: Run tests on pkg module
        run: cd pkg && gotestsum --format testname -- ./...
        env:
          GOCACHE: /tmp/go-build-cache

  go-build:
    needs: [go-lint, go-test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        command: [api, ingest, writer]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true

      - name: Build executable
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOCACHE: /tmp/go-build-cache
        run: |
          output_name="${{ matrix.command }}_executable"
          if [ "$GOOS" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          go build -v -o "$output_name" ./cmd/${{ matrix.command }}

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.command }}-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            ${{ matrix.command }}_executable*
          if-no-files-found: error
