name: Go Build and Test API

on:
  push:
    branches: ["main"]
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "cmd/**"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true # Caches Go modules

      # Explicit build cache - still needed
      - name: Set up Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /tmp/go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-cache-

      - name: Install gotestsum
        run: go install gotest.tools/gotestsum@latest

      - name: Run tests
        run: gotestsum --format testname -- ./...
        env:
          GOCACHE: /tmp/go-build-cache

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
          cache: true # This enables Go module caching

      # Cache build cache to speed up compilations
      - name: Set up Go build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            /tmp/go-build-cache
          key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-build-cache-

      - name: Build API executable for ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          GOCACHE: /tmp/go-build-cache
        run: |
          output_name="myapi_executable"
          if [ "$GOOS" = "windows" ]; then
            output_name="${output_name}.exe"
          fi
          echo "Building for $GOOS/$GOARCH, output: $output_name"
          go build -v -o "$output_name" ./cmd/api/v1

      - name: Upload API executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-v1-executable-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            myapi_executable
            myapi_executable.exe
          if-no-files-found: error
