name: Python Lint and Test

on:
  push:
    branches: ["main"]
    paths:
      - "userator/**"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/**"
  pull_request:
    branches: ["main"]
    paths:
      - "userator/**"
      - "pyproject.toml"
      - "poetry.lock"
      - ".github/workflows/**"
jobs:
  py-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Cache Poetry environment
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --with dev

      - name: Lint with flake8
        run: poetry run flake8 userator/

      - name: Check formatting with black
        run: poetry run black --check userator/

      - name: Check imports with isort
        run: poetry run isort --check-only userator/

  py-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Cache Poetry environment
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --with dev

      - name: Test with pytest
        run: poetry run pytest userator/
